### ISSUE TITLE
Certains contours bloquent le traitement Inter avec un message Python

### ISSUE THREAD

**Issue by jhemmi** [jhemmi/QgisPhysiocapPlugin#21]
Le message 

Traceback (most recent call last):
  File "C:/xx/apps/qgis/./python/plugins\PhysiocapAnalyseur\Physiocap_dialog.py", line 325, in moyenne_inter_parcelles
    physiocap_moyenne_InterParcelles(self)
  File "C:/xx1/apps/qgis/./python/plugins\PhysiocapAnalyseur\Physiocap_inter.py", line 314, in physiocap_moyenne_InterParcelles
    setFilterRect(geom_poly.boundingBox())):
AttributeError: 'NoneType' object has no attribute 'boundingBox'

Est sans doute du à un contour avec un probleme de géometrie (ligne ou point ... ?) 
Attente du jeu de donnée problématique.
**Un message d'erreur Physiocap est créé pour la prochaine version.**

Contournement : corriger la géométrie de votre polygone.

**Comment by jhemmi** [comment]
Semble corrigé depuis 1.3.1 : un message explicite ces cas.
Fermé : pas de nouvelle de l'utilsateur
