### ISSUE TITLE
Problème lors de l'affichage des histogrammes (>> Issue 6)

### ISSUE THREAD

**Issue by AntoninTBL** [jhemmi/QgisPhysiocapPlugin#22]
Bonjour, j'ai toujours le même problème quand j'utilise le code Python, à savoir que je n'arrive pas à créer les histogrammes lors de la création du shapefile:

Une erreur est apparue lors de l'exécution du code Python :

Traceback (most recent call last):
  File "C:/Users/tabela/.qgis2/python/plugins\PhysiocapAnalyseur\Physiocap_dialog.py", line 464, in accept
    retour = self.physiocap_creer_donnees_resultats( details, TRACE_HISTO, recursif, laProjection)
  File "C:/Users/tabela/.qgis2/python/plugins\PhysiocapAnalyseur\Physiocap_dialog.py", line 752, in physiocap_creer_donnees_resultats
    physiocap_tracer_histo( data_histo_sarment, name, 0, 50, "SARMENT au m", "FREQUENCE en %", "HISTOGRAMME NBSARM AVANT TRAITEMENT")
  File "C:/Users/tabela/.qgis2/python/plugins\PhysiocapAnalyseur\Physiocap_CIVC.py", line 369, in physiocap_tracer_histo
    plt.savefig(name)
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\matplotlib\pyplot.py", line 472, in savefig
    return fig.savefig(_args, *_kwargs)
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\matplotlib\figure.py", line 1370, in savefig
    self.canvas.print_figure(_args, *_kwargs)
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 161, in print_figure
    FigureCanvasAgg.print_figure(self, _args, *_kwargs)
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\matplotlib\backend_bases.py", line 2096, in print_figure
    **kwargs)
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\matplotlib\backend_bases.py", line 1915, in print_tif
    image = Image.frombuffer('RGBA', size, buf, 'raw', 'RGBA', 0, 1)
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\PIL\Image.py", line 1851, in frombuffer
    im = new(mode, (1,1))
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\PIL\Image.py", line 1763, in new
    return Image()._new(core.fill(mode, size, color))
  File "C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\PIL\Image.py", line 37, in __getattr__
    raise ImportError("The _imaging C module is not installed")
ImportError: The _imaging C module is not installed

Version de Python :
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Version de QGIS :
2.10.1-Pisa Pisa, d20c5b7

Chemin vers Python : ['C:/PROGRA~1/QGISPI~1/apps/qgis/./python/plugins\processing', 'C:/PROGRA~1/QGISPI~1/apps/qgis/./python', u'C:/Users/tabela/.qgis2/python', u'C:/Users/tabela/.qgis2/python/plugins', 'C:/PROGRA~1/QGISPI~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISPI~1\bin\python27.zip', 'C:\PROGRA~1\QGISPI~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISPI~1\bin', 'C:\PROGRA~1\QGISPI~1\apps\Python27', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\six-1.6.1-py2.7.egg', 'C:\PROGRA~1\QGISPI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'C:/Users/tabela/.qgis2//python', 'C:\Users\tabela\.qgis2\python\plugins\mmqgis/forms', 'C:\PROGRA~1\QGISPI~1\apps\qgis\python\plugins\fTools\tools']

**Comment by jhemmi** [comment]
Ce problème apparaît uniquement avec les version installé dans Osgeo en 2.8 et 2.10.
Une solution est difficile à trouver car je n'ai pas pu reproduire sous 2.12 installé avec OSGEO.

cf issue 6 : https://github.com/jhemmi/QgisPhysiocapPlugin/issues/6

**Comment by jhemmi** [comment]
Bonjour,
Merci de votre utilisation des issues du plugin Physiocap.

Ce problème apparaît uniquement avec les version installé dans Osgeo en 2.8
et 2.10. Une solution est difficile à trouver car je n'ai pas pu reproduire sous
2.12 installé avec OSGEO.

cf issue 6 : https://github.com/jhemmi/QgisPhysiocapPlugin/issues/6

## Meilleures salutations

Jean Hemmi | Valoriser vos données
Attention nouveau numéro de Tel :  +33 768 056 192
Web objectifs.jhemmi.eu

2015-12-03 11:10 GMT+01:00 AntoninTBL notifications@github.com:
